index:
   path: /inicio
   controller: App\Controller\HomeController::index
animales:
   path: /animales/{name?}
   controller: App\Controller\HomeController::animales
   defaults: { name: 'ninguno' }