index:
   path: /inicio
   controller: App\Controller\HomeController::index
animales:
   path: /animales/{name?}/{apellidos?}/{username?}
   controller: App\Controller\HomeController::animales
   defaults: { name: 'No Eres', apellidos: 'Nada', username: 'Nada'}
   methods: [POST,GET]
   requirements:
      name: '[a-zA-Z]+'
      apellidos: '[a-zA-Z]+\s[a-zA-Z]+$'
      username: '[a-zA-Z0-9_-]+'
redirect:
   path: /redirect
   controller: App\Controller\HomeController::redirection

animal_index:
   path: animal/index
   controller: App\Controller\AnimalController::index

animal_save:
   path: animal/save
   controller: App\Controller\AnimalController::save

animal_detail:
   path: animal/{id}
   controller: App\Controller\AnimalController::animal
