<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQMRZchw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQMRZchw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQMRZchw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQMRZchw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQMRZchw\App_KernelDevDebugContainer([
    'container.build_hash' => 'QMRZchw',
    'container.build_id' => 'a9959820',
    'container.build_time' => 1610684875,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQMRZchw');
