<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwOUyjh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwOUyjh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFwOUyjh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFwOUyjh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFwOUyjh\App_KernelDevDebugContainer([
    'container.build_hash' => 'FwOUyjh',
    'container.build_id' => '3bf7e8d1',
    'container.build_time' => 1610171992,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFwOUyjh');
