<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'validate_email' => [['email'], ['_controller' => 'App\\Controller\\AnimalController::validateEmail'], [], [['variable', '/', '[^/]++', 'email', true], ['text', '/validate/email']], [], []],
    'animal_create' => [[], ['_controller' => 'App\\Controller\\AnimalController::create'], [], [['text', '/animal/create']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/inicio']], [], []],
    'animales' => [['name', 'apellidos', 'username'], ['name' => 'No Eres', 'apellidos' => 'Nada', 'username' => 'Nada', '_controller' => 'App\\Controller\\HomeController::animales'], ['name' => '[a-zA-Z]+', 'apellidos' => '[a-zA-Z]+\\s[a-zA-Z]+', 'username' => '[a-zA-Z0-9_-]+'], [['variable', '/', '[a-zA-Z0-9_-]+', 'username', true], ['variable', '/', '[a-zA-Z]+\\s[a-zA-Z]+', 'apellidos', true], ['variable', '/', '[a-zA-Z]+', 'name', true], ['text', '/animales']], [], []],
    'redirect' => [[], ['_controller' => 'App\\Controller\\HomeController::redirection'], [], [['text', '/redirect']], [], []],
    'animal_index' => [[], ['_controller' => 'App\\Controller\\AnimalController::index'], [], [['text', '/animal/index']], [], []],
    'animal_save' => [[], ['_controller' => 'App\\Controller\\AnimalController::save'], [], [['text', '/animal/save']], [], []],
    'animal_detail' => [['id'], ['_controller' => 'App\\Controller\\AnimalController::animal'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/animal']], [], []],
    'animal_update' => [['id'], ['_controller' => 'App\\Controller\\AnimalController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/animal/update']], [], []],
    'animal_delete' => [['id'], ['_controller' => 'App\\Controller\\AnimalController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/animal/delete']], [], []],
];
